### ISSUE TITLE
Práctica EDT

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-team-remi#1]
[Práctica EDT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-team-remi/files/9833487/Practica.EDT.pdf)

**Comment by Rosa218** [comment]
Calificacion:20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
